# Copyright (c) 2020 EXASOL
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

name: Linux CI (asan/ubsan)

on:
  push:
    branches:
      # Development and release branches
      - main
      - release**
      # Bors branches
      - trying
      - staging

jobs:
  build:
    name: github/linux/sanitizers/fast
    runs-on: ubuntu-latest
    container: pikaorg/pika-ci-base:13

    steps:
    - uses: actions/checkout@v3
    - name: Update apt repositories for ccache
      run: apt update
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ccache-linux-sanitizers
    - name: Check out pika
      uses: actions/checkout@v3
      with:
        repository: pika-org/pika
        ref: 0.11.0
        path: pika
    - name: Install pika
      shell: bash
      working-directory: pika
      run: |
          cmake \
              . \
              -Bbuild \
              -GNinja \
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
              -DCMAKE_BUILD_TYPE=Debug \
              -DPIKA_WITH_MALLOC=system \
              -DPIKA_WITH_SANITIZERS=On \
              -DPIKA_WITH_STACKOVERFLOW_DETECTION=Off \
              -DCMAKE_CXX_FLAGS="-fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer"
          cmake --build build --target install
    - name: Configure
      shell: bash
      run: |
          cmake \
              . \
              -Bbuild \
              -GNinja \
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
              -DCMAKE_BUILD_TYPE=Debug \
              -DPIKA_ALGORITHMS_WITH_EXAMPLES=ON \
              -DPIKA_ALGORITHMS_WITH_TESTS=ON \
              -DPIKA_ALGORITHMS_WITH_TESTS_EXAMPLES=ON \
              -DPIKA_ALGORITHMS_WITH_TESTS_MAX_THREADS=2 \
              -DPIKA_ALGORITHMS_WITH_COMPILER_WARNINGS=ON \
              -DPIKA_ALGORITHMS_WITH_COMPILER_WARNINGS_AS_ERRORS=ON \
              -DPIKA_ALGORITHMS_WITH_SANITIZERS=On \
              -DCMAKE_CXX_FLAGS="-fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer"
    - name: Build
      shell: bash
      run: |
          cmake --build build --target all
          cmake --build build --target examples
    - name: Test
      shell: bash
      run: |
          export ASAN_OPTIONS=fast_unwind_on_malloc=0
          export LSAN_OPTIONS=suppressions=$PWD/tools/asan.supp
          export UBSAN_OPTIONS=print_stacktrace=1,suppressions=$PWD/tools/ubsan.supp
          cd build
          ctest \
            --timeout 120 \
            --output-on-failure \
            --tests-regex tests.examples
