# Copyright (c) 2021 ETH Zurich
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

name: Linux CI (HIP, Debug)

on:
  push:
    branches:
      # Development and release branches
      - main
      - release**
      # Bors branches
      - trying
      - staging

jobs:
  build:
    name: github/linux/hip/fast
    runs-on: ubuntu-latest
    container: pikaorg/pika-ci-hip:6
    steps:
    - uses: actions/checkout@v2
    - name: Update apt repositories for ccache
      run: apt update
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ccache-linux-hip
    - name: Check out pika
      uses: actions/checkout@v3
      with:
        repository: pika-org/pika
        ref: 0.11.0
        path: pika
    - name: Install pika
      shell: bash
      working-directory: pika
      run: |
          cmake \
              . \
              -Bbuild \
              -GNinja \
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
              -DCMAKE_BUILD_TYPE=Debug \
              -DPIKA_WITH_HIP=ON \
              -DPIKA_WITH_MALLOC=system
          cmake --build build --target install
    - name: Configure
      shell: bash
      run: |
          cmake \
              . \
              -Bbuild \
              -GNinja \
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
              -DCMAKE_BUILD_TYPE=Debug \
              -DPIKA_ALGORITHMS_WITH_EXAMPLES=ON \
              -DPIKA_ALGORITHMS_WITH_TESTS=ON \
              -DPIKA_ALGORITHMS_WITH_TESTS_UNIT=ON \
              -DPIKA_ALGORITHMS_WITH_TESTS_BENCHMARKS=ON \
              -DPIKA_ALGORITHMS_WITH_TESTS_REGRESSIONS=ON \
              -DPIKA_ALGORITHMS_WITH_TESTS_EXAMPLES=ON \
              -DPIKA_ALGORITHMS_WITH_TESTS_MAX_THREADS=2 \
              -DPIKA_ALGORITHMS_WITH_COMPILER_WARNINGS=ON \
              -DPIKA_ALGORITHMS_WITH_COMPILER_WARNINGS_AS_ERRORS=ON
    - name: Build
      shell: bash
      run: |
          cmake --build build --target all
          cmake --build build --target examples
