# Copyright (c) 2020-2022 ETH Zurich
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

name: macOS CI (Debug)

on:
  push:
    branches:
      # Development and release branches
      - main
      - release**
      # Bors branches
      - trying
      - staging

jobs:
  build_and_test:
    name: github/macos/debug
    runs-on: macos-latest
    steps:
    - name: Install dependencies
      run: |
          # Workaround for https://github.com/actions/setup-python/issues/577
          rm /usr/local/bin/2to3*
          rm /usr/local/bin/idle3*
          rm /usr/local/bin/pydoc3*
          rm /usr/local/bin/python3*

          export HOMEBREW_NO_INSTALL_CLEANUP=TRUE
          brew upgrade
          brew update
          brew install boost cmake fmt hwloc ninja
    - uses: actions/checkout@v3
    - name: Check out pika
      uses: actions/checkout@v3
      with:
        repository: pika-org/pika
        ref: 0.11.0
        path: pika
    - name: Install pika
      shell: bash
      working-directory: pika
      run: |
          cmake \
              . \
              -Bbuild \
              -GNinja \
              -DCMAKE_BUILD_TYPE=Debug \
              -DPIKA_WITH_MALLOC=system
          cmake --build build --target install
    - name: Configure
      shell: bash
      run: |
          cmake \
              . \
              -Bbuild \
              -GNinja \
              -DCMAKE_BUILD_TYPE=Debug \
              -DPIKA_ALGORITHMS_WITH_EXAMPLES=ON \
              -DPIKA_ALGORITHMS_WITH_TESTS=ON \
              -DPIKA_ALGORITHMS_WITH_TESTS_HEADERS=OFF \
              -DPIKA_ALGORITHMS_WITH_PARALLEL_TESTS_BIND_NONE=ON \
              -DPIKA_ALGORITHMS_WITH_TESTS_MAX_THREADS=3 \
              -DPIKA_ALGORITHMS_WITH_MALLOC=system \
              -DPIKA_ALGORITHMS_WITH_CHECK_MODULE_DEPENDENCIES=ON \
              -DPIKA_ALGORITHMS_WITH_COMPILER_WARNINGS=ON \
              -DPIKA_ALGORITHMS_WITH_COMPILER_WARNINGS_AS_ERRORS=On
    - name: Build
      shell: bash
      run: |
          cmake --build build --target all
          cmake --build build --target examples
          cmake --build build --target tests
    - name: Test
      shell: bash
      run: |
          cd build
          ctest \
            --timeout 300 \
            --output-on-failure
